# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  crossover-source = {
    pname = "crossover-source";
    version = "26.3.0";
    src = fetchurl {
      url = "https://media.codeweavers.com/pub/crossover/source/crossover-sources-26.3.0.tar.gz";
      sha256 = "sha256-rJnIyks4SPPoF4QTXwI98ma2HCNFcm6lWlCz4DDdaHI=";
    };
  };
  wine-master = {
    pname = "wine-master";
    version = "eba89375a0515957701928faac0f5007ef638b04";
    src = fetchgit {
      url = "https://gitlab.winehq.org/wine/wine.git";
      rev = "eba89375a0515957701928faac0f5007ef638b04";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-K48LqYG3stz0AKzHMXz+TKmlr4aQoS9ispSiMHZgNhw=";
    };
    date = "2026-10-05";
  };
  wine-stable = {
    pname = "wine-stable";
    version = "db11d0fe6a169c457e23d007e20404643d067aa8";
    src = fetchgit {
      url = "https://gitlab.winehq.org/wine/wine.git";
      rev = "db11d0fe6a169c457e23d007e20404643d067aa8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3jJ2paulqgMLyLR8g5bxwJuuusAMZSrnw+X+nFhYt+c=";
    };
    date = "2026-01-13";
  };
}
