# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  crossover-source = {
    pname = "crossover-source";
    version = "26.3.0";
    src = fetchurl {
      url = "https://media.codeweavers.com/pub/crossover/source/crossover-sources-26.3.0.tar.gz";
      sha256 = "sha256-rJnIyks4SPPoF4QTXwI98ma2HCNFcm6lWlCz4DDdaHI=";
    };
  };
  wine-master = {
    pname = "wine-master";
    version = "36b6a2cf679fb395f668a917b76537190e212d9c";
    src = fetchgit {
      url = "https://gitlab.winehq.org/wine/wine.git";
      rev = "36b6a2cf679fb395f668a917b76537190e212d9c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PXk0yjmLgLbZ2EGUyFoK67zmqFWL7eVQfbuCyVgyU3w=";
    };
    date = "2026-09-04";
  };
  wine-stable = {
    pname = "wine-stable";
    version = "db11d0fe6a169c457e23d007e20404643d067aa8";
    src = fetchgit {
      url = "https://gitlab.winehq.org/wine/wine.git";
      rev = "db11d0fe6a169c457e23d007e20404643d067aa8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3jJ2paulqgMLyLR8g5bxwJuuusAMZSrnw+X+nFhYt+c=";
    };
    date = "2026-01-13";
  };
}
