# SPDX-FileCopyrightText: 2026 Claire Tam <claire2026t@posteo.net>
#
# SPDX-License-Identifier: GPL-3.0-only

name: hestia vs magic-nix-cache benchmark

on:
  workflow_dispatch:

jobs:
  cache-race:
    strategy:
      fail-fast: false
      matrix:
        cache: ["magic-nix-cache", "hestia"]

    runs-on: macos-15

    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35

      - name: Start Magic Nix Cache
        if: matrix.cache == 'magic-nix-cache'
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Start Hestia
        if: matrix.cache == 'hestia'
        uses: Mic92/hestia@v3

      - name: Dev Shell Instantiation
        run: |
          echo "Benchmarking ${{ matrix.cache }}..."
          time nix develop .#default --command echo "hello world"
