# SPDX-FileCopyrightText: 2026 Claire Tam <claire2026t@posteo.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Upload ccache as Artifact

on:
  workflow_dispatch:
    inputs:
      cache_key:
        description: "Exact Cache Key to download (e.g., macOS-ccache-123456-1)"
        required: true
        type: string

jobs:
  cache-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Restore ccache
        uses: actions/cache/restore@v6
        with:
          path: .ccache
          key: ${{ inputs.cache_key }}
          fail-on-cache-miss: true

      - name: Upload ccache as artifact
        uses: actions/upload-artifact@v7
        with:
          name: extracted-ccache-artifact
          include-hidden-files: true
          path: .ccache
          retention-days: 7
